# Generated by Django 2.2.17 on 2021-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSendlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '短信发送记录',
                'verbose_name_plural': '短信发送记录',
                'db_table': 'tb_sms_send_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
