# Generated by Django 2.2.17 on 2021-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('content', models.CharField(max_length=255, verbose_name='留言内容')),
                ('type', models.CharField(default='mobile', max_length=6, verbose_name='留言端')),
                ('username', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否阅读')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'db_table': 'tb_feedback',
            },
        ),
    ]
